-- Trivandrum Top 10 - Supabase Schema
-- SECURITY: All INSERTs go through Edge Function (supabase/functions/track-event)
-- See: supabase/migrations/001_secure_rls_policies.sql for RLS policy updates

-- ============================================================
-- TABLE: locality_views
-- Tracks every time a user views a locality page
-- ============================================================
create table if not exists locality_views (
  id bigint generated by default as identity primary key,
  locality_name text not null,
  viewed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  session_id text -- Anonymous "Guest ID"
);

alter table locality_views enable row level security;

-- SECURE: Only service role (Edge Function) can INSERT
-- Run migration 001_secure_rls_policies.sql to apply these policies
create policy "Service role insert only" on locality_views
  for insert to service_role with check (true);

-- Public can READ analytics data
create policy "Enable read access for all" on locality_views
  for select using (true);

-- ============================================================
-- TABLE: site_events
-- Generic event tracking (page views, interactions, searches)
-- ============================================================
create table if not exists site_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  event_type text not null, -- 'page_view', 'interaction', 'search', etc.
  event_name text not null, -- 'view_page', 'marker_clicked', etc.
  page_path text,           -- '#/localities', '#/map'
  session_id text,          -- Persistent anonymous ID
  metadata jsonb,           -- Extra info (e.g., search query, weight values)
  user_agent text           -- Device info
);

alter table site_events enable row level security;

-- SECURE: Only service role (Edge Function) can INSERT
create policy "Service role insert only" on site_events
  for insert to service_role with check (true);

-- Public can READ analytics data
create policy "Enable read for all users" on site_events
  for select using (true);

-- ============================================================
-- TABLE: rate_limits
-- Prevents abuse of the Edge Function endpoint
-- ============================================================
create table if not exists rate_limits (
  id bigint generated by default as identity primary key,
  session_id text not null,
  endpoint text not null,
  request_count int default 1,
  window_start timestamp with time zone default now(),
  unique(session_id, endpoint)
);

alter table rate_limits enable row level security;

-- Only service role can manage rate limits
create policy "Service role only" on rate_limits
  for all to service_role
  using (true) with check (true);
