-- Trivandrum Top 10 - Supabase Schema

-- 1. Create a table to track views (for Bot & ML)
-- This stores every time a user views a locality, along with a session ID for anonymous tracking.
create table if not exists locality_views (
  id bigint generated by default as identity primary key,
  locality_name text not null,
  viewed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  session_id text -- Anonymous "Guest ID"
);

-- 2. Enable Row Level Security (Security best practice)
alter table locality_views enable row level security;

-- 3. Policy: Allow anyone (even anonymous users) to insert views
-- This is critical for our public site to log data without login.
create policy "Enable insert for everyone" on locality_views for insert with check (true);

-- 4. Policy: Allow reading analytics
-- We might want to restrict this later, but useful for dev now.
create policy "Enable read access for all" on locality_views for select using (true);
