-- ============================================================
-- MIGRATION: Secure RLS Policies for Analytics Tables
-- Run this in Supabase SQL Editor (Dashboard > SQL Editor)
-- ============================================================

-- ============================================================
-- STEP 1: Drop the insecure public INSERT policies
-- ============================================================

-- Drop insecure INSERT policy on locality_views
DROP POLICY IF EXISTS "Enable insert for everyone" ON locality_views;

-- Drop insecure INSERT policy on site_events
DROP POLICY IF EXISTS "Enable insert for all users" ON site_events;

-- ============================================================
-- STEP 2: Create secure INSERT policies (service role only)
-- These allow only authenticated service role to insert
-- ============================================================

-- Only service role (Edge Functions) can insert into locality_views
CREATE POLICY "Service role insert only" ON locality_views
  FOR INSERT
  TO service_role
  WITH CHECK (true);

-- Only service role (Edge Functions) can insert into site_events
CREATE POLICY "Service role insert only" ON site_events
  FOR INSERT
  TO service_role
  WITH CHECK (true);

-- ============================================================
-- STEP 3: Keep SELECT policies for reading analytics
-- (These are safe - reading analytics data is fine)
-- ============================================================

-- Verify SELECT policies exist (these should already be there)
-- If not, uncomment and run:
-- CREATE POLICY "Enable read access for all" ON locality_views FOR SELECT USING (true);
-- CREATE POLICY "Enable read for all users" ON site_events FOR SELECT USING (true);

-- ============================================================
-- STEP 4: Create rate limiting table (optional but recommended)
-- ============================================================

CREATE TABLE IF NOT EXISTS rate_limits (
  id bigint generated by default as identity primary key,
  session_id text not null,
  endpoint text not null,
  request_count int default 1,
  window_start timestamp with time zone default now(),
  UNIQUE(session_id, endpoint)
);

-- Enable RLS on rate_limits
ALTER TABLE rate_limits ENABLE ROW LEVEL SECURITY;

-- Only service role can manage rate limits
CREATE POLICY "Service role only" ON rate_limits
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- ============================================================
-- VERIFICATION: Check the policies after running
-- ============================================================
-- Run this to verify:
-- SELECT tablename, policyname, permissive, roles, cmd
-- FROM pg_policies
-- WHERE tablename IN ('locality_views', 'site_events', 'rate_limits');
